export{ default as portfolio1 } from './portfolio1.png'
export { default as portfolio2 } from './portfolio2.png'
export { default as portfolio3 } from './portfolio3.png'
export { default as portfolio4 } from './portfolio4.png'
export { default as portfolio5 } from './portfolio5.png'
export { default as portfolio7 } from './portfolio7.png'
export { default as portfolio8 } from './portfolio8.png'
export { default as portfolio9 } from './portfolio9.png'
export { default as portfolio10 } from './portfolio10.png'
export { default as portfolio11 } from './portfolio11.png'
