export{ default as portfolio1 } from './portfolio1.jpg'
export { default as portfolio2 } from './portfolio2.jpg'
export { default as portfolio3 } from './portfolio3.jpg'
export { default as portfolio4 } from './portfolio4.jpg'
export { default as portfolio5 } from './portfolio5.jpg'
export { default as portfolio6 } from './portfolio6.jpg'
