export {  default as Header} from './header/Header'
export {  default as Aboutme} from './aboutme/Aboutme'
export {  default as Services} from './services/Services'
export {  default as Portfolio} from './portfolio/Portfolio'
export {  default as Contact} from './contact/Contact'
export {  default as Footer} from './footer/Footer'
